// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: price.proto
// Protobuf Java Version: 4.29.1

package messages;

public interface PriceDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.PriceDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp datetime = 1;</code>
   * @return Whether the datetime field is set.
   */
  boolean hasDatetime();
  /**
   * <code>.google.protobuf.Timestamp datetime = 1;</code>
   * @return The datetime.
   */
  com.google.protobuf.Timestamp getDatetime();
  /**
   * <code>.google.protobuf.Timestamp datetime = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDatetimeOrBuilder();

  /**
   * <code>float price_per_gram = 2;</code>
   * @return The pricePerGram.
   */
  float getPricePerGram();

  /**
   * <code>float price_per_ounce = 3;</code>
   * @return The pricePerOunce.
   */
  float getPricePerOunce();
}
