// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: price.proto
// Protobuf Java Version: 4.29.1

package messages;

/**
 * Protobuf type {@code messages.PriceDetails}
 */
public final class PriceDetails extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:messages.PriceDetails)
    PriceDetailsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      PriceDetails.class.getName());
  }
  // Use PriceDetails.newBuilder() to construct.
  private PriceDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PriceDetails() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return messages.Price.internal_static_messages_PriceDetails_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return messages.Price.internal_static_messages_PriceDetails_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            messages.PriceDetails.class, messages.PriceDetails.Builder.class);
  }

  private int bitField0_;
  public static final int DATETIME_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp datetime_;
  /**
   * <code>.google.protobuf.Timestamp datetime = 1;</code>
   * @return Whether the datetime field is set.
   */
  @java.lang.Override
  public boolean hasDatetime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp datetime = 1;</code>
   * @return The datetime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDatetime() {
    return datetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : datetime_;
  }
  /**
   * <code>.google.protobuf.Timestamp datetime = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDatetimeOrBuilder() {
    return datetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : datetime_;
  }

  public static final int PRICE_PER_GRAM_FIELD_NUMBER = 2;
  private float pricePerGram_ = 0F;
  /**
   * <code>float price_per_gram = 2;</code>
   * @return The pricePerGram.
   */
  @java.lang.Override
  public float getPricePerGram() {
    return pricePerGram_;
  }

  public static final int PRICE_PER_OUNCE_FIELD_NUMBER = 3;
  private float pricePerOunce_ = 0F;
  /**
   * <code>float price_per_ounce = 3;</code>
   * @return The pricePerOunce.
   */
  @java.lang.Override
  public float getPricePerOunce() {
    return pricePerOunce_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getDatetime());
    }
    if (java.lang.Float.floatToRawIntBits(pricePerGram_) != 0) {
      output.writeFloat(2, pricePerGram_);
    }
    if (java.lang.Float.floatToRawIntBits(pricePerOunce_) != 0) {
      output.writeFloat(3, pricePerOunce_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDatetime());
    }
    if (java.lang.Float.floatToRawIntBits(pricePerGram_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, pricePerGram_);
    }
    if (java.lang.Float.floatToRawIntBits(pricePerOunce_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, pricePerOunce_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof messages.PriceDetails)) {
      return super.equals(obj);
    }
    messages.PriceDetails other = (messages.PriceDetails) obj;

    if (hasDatetime() != other.hasDatetime()) return false;
    if (hasDatetime()) {
      if (!getDatetime()
          .equals(other.getDatetime())) return false;
    }
    if (java.lang.Float.floatToIntBits(getPricePerGram())
        != java.lang.Float.floatToIntBits(
            other.getPricePerGram())) return false;
    if (java.lang.Float.floatToIntBits(getPricePerOunce())
        != java.lang.Float.floatToIntBits(
            other.getPricePerOunce())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDatetime()) {
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDatetime().hashCode();
    }
    hash = (37 * hash) + PRICE_PER_GRAM_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPricePerGram());
    hash = (37 * hash) + PRICE_PER_OUNCE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPricePerOunce());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static messages.PriceDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static messages.PriceDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static messages.PriceDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static messages.PriceDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static messages.PriceDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static messages.PriceDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static messages.PriceDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static messages.PriceDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static messages.PriceDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static messages.PriceDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static messages.PriceDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static messages.PriceDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(messages.PriceDetails prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code messages.PriceDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:messages.PriceDetails)
      messages.PriceDetailsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return messages.Price.internal_static_messages_PriceDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return messages.Price.internal_static_messages_PriceDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              messages.PriceDetails.class, messages.PriceDetails.Builder.class);
    }

    // Construct using messages.PriceDetails.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDatetimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      datetime_ = null;
      if (datetimeBuilder_ != null) {
        datetimeBuilder_.dispose();
        datetimeBuilder_ = null;
      }
      pricePerGram_ = 0F;
      pricePerOunce_ = 0F;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return messages.Price.internal_static_messages_PriceDetails_descriptor;
    }

    @java.lang.Override
    public messages.PriceDetails getDefaultInstanceForType() {
      return messages.PriceDetails.getDefaultInstance();
    }

    @java.lang.Override
    public messages.PriceDetails build() {
      messages.PriceDetails result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public messages.PriceDetails buildPartial() {
      messages.PriceDetails result = new messages.PriceDetails(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(messages.PriceDetails result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.datetime_ = datetimeBuilder_ == null
            ? datetime_
            : datetimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pricePerGram_ = pricePerGram_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pricePerOunce_ = pricePerOunce_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof messages.PriceDetails) {
        return mergeFrom((messages.PriceDetails)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(messages.PriceDetails other) {
      if (other == messages.PriceDetails.getDefaultInstance()) return this;
      if (other.hasDatetime()) {
        mergeDatetime(other.getDatetime());
      }
      if (other.getPricePerGram() != 0F) {
        setPricePerGram(other.getPricePerGram());
      }
      if (other.getPricePerOunce() != 0F) {
        setPricePerOunce(other.getPricePerOunce());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDatetimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 21: {
              pricePerGram_ = input.readFloat();
              bitField0_ |= 0x00000002;
              break;
            } // case 21
            case 29: {
              pricePerOunce_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp datetime_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> datetimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     * @return Whether the datetime field is set.
     */
    public boolean hasDatetime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     * @return The datetime.
     */
    public com.google.protobuf.Timestamp getDatetime() {
      if (datetimeBuilder_ == null) {
        return datetime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : datetime_;
      } else {
        return datetimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     */
    public Builder setDatetime(com.google.protobuf.Timestamp value) {
      if (datetimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        datetime_ = value;
      } else {
        datetimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     */
    public Builder setDatetime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (datetimeBuilder_ == null) {
        datetime_ = builderForValue.build();
      } else {
        datetimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     */
    public Builder mergeDatetime(com.google.protobuf.Timestamp value) {
      if (datetimeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          datetime_ != null &&
          datetime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDatetimeBuilder().mergeFrom(value);
        } else {
          datetime_ = value;
        }
      } else {
        datetimeBuilder_.mergeFrom(value);
      }
      if (datetime_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     */
    public Builder clearDatetime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      datetime_ = null;
      if (datetimeBuilder_ != null) {
        datetimeBuilder_.dispose();
        datetimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDatetimeBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDatetimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDatetimeOrBuilder() {
      if (datetimeBuilder_ != null) {
        return datetimeBuilder_.getMessageOrBuilder();
      } else {
        return datetime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : datetime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp datetime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDatetimeFieldBuilder() {
      if (datetimeBuilder_ == null) {
        datetimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDatetime(),
                getParentForChildren(),
                isClean());
        datetime_ = null;
      }
      return datetimeBuilder_;
    }

    private float pricePerGram_ ;
    /**
     * <code>float price_per_gram = 2;</code>
     * @return The pricePerGram.
     */
    @java.lang.Override
    public float getPricePerGram() {
      return pricePerGram_;
    }
    /**
     * <code>float price_per_gram = 2;</code>
     * @param value The pricePerGram to set.
     * @return This builder for chaining.
     */
    public Builder setPricePerGram(float value) {

      pricePerGram_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>float price_per_gram = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPricePerGram() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pricePerGram_ = 0F;
      onChanged();
      return this;
    }

    private float pricePerOunce_ ;
    /**
     * <code>float price_per_ounce = 3;</code>
     * @return The pricePerOunce.
     */
    @java.lang.Override
    public float getPricePerOunce() {
      return pricePerOunce_;
    }
    /**
     * <code>float price_per_ounce = 3;</code>
     * @param value The pricePerOunce to set.
     * @return This builder for chaining.
     */
    public Builder setPricePerOunce(float value) {

      pricePerOunce_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float price_per_ounce = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPricePerOunce() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pricePerOunce_ = 0F;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messages.PriceDetails)
  }

  // @@protoc_insertion_point(class_scope:messages.PriceDetails)
  private static final messages.PriceDetails DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new messages.PriceDetails();
  }

  public static messages.PriceDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PriceDetails>
      PARSER = new com.google.protobuf.AbstractParser<PriceDetails>() {
    @java.lang.Override
    public PriceDetails parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PriceDetails> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PriceDetails> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public messages.PriceDetails getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

