// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: price.proto
// Protobuf Java Version: 4.29.1

package messages;

public interface PriceSnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messages.PriceSnapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source = 1;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 1;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>.google.protobuf.Timestamp datetime = 2;</code>
   * @return Whether the datetime field is set.
   */
  boolean hasDatetime();
  /**
   * <code>.google.protobuf.Timestamp datetime = 2;</code>
   * @return The datetime.
   */
  com.google.protobuf.Timestamp getDatetime();
  /**
   * <code>.google.protobuf.Timestamp datetime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDatetimeOrBuilder();

  /**
   * <code>float price = 3;</code>
   * @return The price.
   */
  float getPrice();
}
