// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: price.proto
// Protobuf Java Version: 4.29.1

package messages;

public final class Price {
  private Price() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      Price.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_PriceSnapshot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_PriceSnapshot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_PriceDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_PriceDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013price.proto\022\010messages\032\037google/protobuf" +
      "/timestamp.proto\"\\\n\rPriceSnapshot\022\016\n\006sou" +
      "rce\030\001 \001(\t\022,\n\010datetime\030\002 \001(\0132\032.google.pro" +
      "tobuf.Timestamp\022\r\n\005price\030\003 \001(\002\"m\n\014PriceD" +
      "etails\022,\n\010datetime\030\001 \001(\0132\032.google.protob" +
      "uf.Timestamp\022\026\n\016price_per_gram\030\002 \001(\002\022\027\n\017" +
      "price_per_ounce\030\003 \001(\002B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_messages_PriceSnapshot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_PriceSnapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_PriceSnapshot_descriptor,
        new java.lang.String[] { "Source", "Datetime", "Price", });
    internal_static_messages_PriceDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_messages_PriceDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_PriceDetails_descriptor,
        new java.lang.String[] { "Datetime", "PricePerGram", "PricePerOunce", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
